version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /c/Workspace/Dev/UpTech/upsentry-map:/workspace:ro
    environment:
      - NODE_ENV=development
      - PORT=8088
    working_dir: /workspace
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8087:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8088
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge